services:
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1029
      - PGID=65536
      - TZ=Europe/London
    volumes:
      - /volume1/docker/tautulli:/config
    ports:
      - 8181:8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=PathPrefix(`/tautulli/`)"
    networks:
      - synobridge
      - traefik_proxy
    restart: unless-stopped
networks:
  synobridge:
    external: true
  traefik_proxy:
    external: true