services:  
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1029
      - PGID=65536
      - TZ=Europe/London
      - WEBUI_PORT=8090
    volumes:
      - /volume1/docker/qbittorrent:/config
      - /volume1/ingest/torrents:/data/torrents
    ports:
      - 8090:8090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=PathPrefix(`/qbittorrent/`)"
    networks:
      - gluetun
      - traefik_proxy
    restart: unless-stopped
networks:
  gluetun:
    external: true
  traefik_proxy:
    external: true
