services:
  traefik:
    image: traefik:latest
    container_name: traefik
    depends_on:
      - socket-proxy
    restart: unless-stopped
    networks:
      synobridge: {}
      traefik_proxy: {}
      traefik_socket: {}
    ports:
      - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      # - "traefik.frontend.auth.basic=${BASIC_AUTH}"
    volumes:
      # - /volume1/docker/traefik:/etc/traefik
      - ./traefik.yml:/etc/traefik/traefik.yml
  traefik-home:
    image: ghcr.io/santimar/traefik-home:latest
    container_name: traefik-home
    environment:
      DOCKER_HOST: "tcp://socket-proxy:2375"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-home.rule=Path(`/`)"
    networks:
      - traefik_proxy
      - traefik_socket
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1
      INFO: 1
    networks:
      - traefik_socket
networks:
  synobridge:
    external: true
  # For containers only accessed through Traefik
  traefik_proxy:
    external: true
  # For Traefik and the socket-proxy only
  traefik_socket:
    internal: true