services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PGID=65536
      - PUID=1029
      - TZ=Europe/London
    volumes:
      - /volume1/docker/sonarr:/config
      - /volume1/malachit:/data
    ports:
      - 8989:8989
    network_mode: synobridge
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PGID=65536
      - PUID=1029
      - TZ=Europe/London
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/malachit:/data
    ports:
      - 7878:7878
    network_mode: synobridge
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PGID=65536
      - PUID=1029
      - TZ=Europe/London
    volumes:
      - /volume1/docker/bazarr:/config
      - /volume1/malachit:/data
    ports:
      - 6767:6767
    network_mode: synobridge
    restart: unless-stopped
