services:
  actual-server:
    image: actualbudget/actual-server:latest
    env_file:
      - /defaults.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual-server.rule=Host(`actual.${DOMAIN_NAME}`)"
      - "traefik.http.routers.actual-server.entrypoints=websecure"
      - "traefik.http.routers.actual-server.tls=true"
      - "traefik.http.routers.actual-server.middlewares=chain-noauth@docker"
      - "traefik.http.routers.actual-server.service=actual-server-svc"
      - "traefik.http.services.actual-server-svc.loadbalancer.server.port=5006"
    networks:
      - traefik
    volumes:
      - $DATA_DIR/actual/data:/data
    restart: unless-stopped
networks:
  traefik:
    external: true
