services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/sonarr:/config
      - $SHARE_DIR/media:/data/media
      - $INGEST_DIR/torrents:/data/torrents
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=websecure"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.sonarr.middlewares=chain-forwardauth-plex@docker"
      - "traefik.http.services.sonarr-arrs.loadbalancer.server.port=8989"
    networks:
      - synobridge
      - traefik
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/radarr:/config
      - $SHARE_DIR/media:/data/media
      - $INGEST_DIR/torrents:/data/torrents
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=websecure"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.radarr.middlewares=chain-forwardauth-plex@docker"
      - "traefik.http.services.radarr-arrs.loadbalancer.server.port=7878"
    networks:
      - synobridge
      - traefik
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/bazarr:/config
      - $SHARE_DIR/media:/data/media
      - $INGEST_DIR/torrents:/data/torrents
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.entrypoints=websecure"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.bazarr.middlewares=chain-forwardauth-plex@docker"
      - "traefik.http.services.bazarr-arrs.loadbalancer.server.port=6767"
    networks:
      - synobridge
      - traefik
    restart: unless-stopped
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/prowlarr:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN_NAME}`)"
      - "traefik.http.routers.prowlarr.middlewares=chain-forwardauth-plex@docker"
      - "traefik.http.services.prowlarr-arrs.loadbalancer.server.port=9696"
    networks:
      - synobridge
      - traefik
    restart: unless-stopped
networks:
  synobridge:
    external: true
  traefik:
    external: true
