services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8090:8090
    volumes:
      - $DATA_DIR/gluetun:/gluetun
    env_file:
      - /defaults.env
      - ../../stack.env
    networks:
      - synobridge
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent.tls=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN_NAME}`)"
      - "traefik.http.services.qbittorrent-ingest.loadbalancer.server.port=8090"
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8090
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/qbittorrent:/config
      - $INGEST_DIR/torrents:/data/torrents
    network_mode: service:gluetun
    restart: unless-stopped
networks:
  synobridge:
    external: true
  # For containers going through VPN
  traefik:
    external: true
