services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - $DATA_DIR/gluetun:/gluetun
    env_file:
      - /defaults.env
      - ../../stack.env
    networks:
      - synobridge
      - default
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8090
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/qbittorrent:/config
      - $INGEST_DIR/torrents:/data/torrents
    network_mode: service:gluetun
    restart: unless-stopped
  flood:
    image: jesec/flood:master
    container_name: flood
    user: ${PUID}:${PGID}
    networks:
      - default
      - traefik
    env_file:
      - /defaults.env
      - ../../stack.env
    command: --auth none --port 3010 --allowedpath /data --qburl http://gluetun:8090
    environment:
      - HOME=/config
    volumes:
      - $DATA_DIR/flood/config:/config
      - $INGEST_DIR/torrents:/data/torrents
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flood.entrypoints=websecure"
      - "traefik.http.routers.flood.tls=true"
      - "traefik.http.routers.flood.rule=Host(`flood.${DOMAIN_NAME}`)"
      - "traefik.http.routers.flood.middlewares=chain-forwardauth@docker"
      - "traefik.http.services.flood-ingest.loadbalancer.server.port=3010"
    restart: unless-stopped
networks:
  synobridge:
    external: true
  traefik:
    external: true
  default:
