services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/plex:/config
      - $SHARE_DIR/media:/media
    ports:
      - 32400:32400
      # - 1900:1900/udp
      - 53533:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.rule=Host(`plex.${DOMAIN_NAME}`)"
      - "traefik.http.services.plex-plex.loadbalancer.server.port=32400"
    networks:
      - synobridge
      - traefik
    restart: unless-stopped
  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    env_file:
      - /defaults.env
    volumes:
      - $DATA_DIR/tautulli:/config
    ports:
      - 8181:8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.${DOMAIN_NAME}`)"
      - "traefik.http.services.tautulli-plex.loadbalancer.server.port=8181"
    networks:
      - synobridge
      - traefik
    restart: unless-stopped
networks:
  synobridge:
    external: true
  traefik:
    external: true
