services:
  speedtest-tracker:
    image: linuxserver/speedtest-tracker:latest
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - PUBLIC_DASHBOARD=true
      - APP_KEY=${APP_KEY}
      - DB_DATABASE=${SPEEDTEST_TRACKER_DB}
      - DB_USERNAME=${SPEEDTEST_TRACKER_DB_USER}
      - DB_PASSWORD=${SPEEDTEST_TRACKER_DB_PASS}
      - SPEEDTEST_SCHEDULE=${SPEEDTEST_SCHEDULE}
      - SPEEDTEST_SERVERS=${SPEEDTEST_SERVERS}
    env_file:
      - /defaults.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest-tracker.entrypoints=websecure"
      - "traefik.http.routers.speedtest-tracker.tls=true"
      - "traefik.http.routers.speedtest-tracker.rule=Host(`speedtest-tracker.${DOMAIN_NAME}`)"
      - "traefik.http.routers.speedtest-tracker.service=speedtest-tracker"
      - "traefik.http.services.speedtest-tracker.loadbalancer.server.port=80"
    networks:
      - traefik
      - default
    volumes:
      - $DATA_DIR/speedtest-tracker:/config
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${SPEEDTEST_TRACKER_DB}
      - POSTGRES_USER=${SPEEDTEST_TRACKER_DB_USER}
      - POSTGRES_PASSWORD=${SPEEDTEST_TRACKER_DB_PASS}
    env_file:
      - /defaults.env
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  default:
  traefik:
    external: true
volumes:
  pgdata:
