services:
  tubearchivist:
    container_name: tubearchivist
    image: bbilly1/tubearchivist
    volumes:
      - $SHARE_DIR/media/youtube:/youtube
      - cache:/cache
    networks:
      - traefik
      - default
    env_file:
      - /defaults.env
    environment:
      - ES_URL=http://elasticsearch:9200
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - REDIS_HOST=redis
      - HOST_UID=1029
      - HOST_GID=65536
      - TA_HOST=tubearchivist.${DOMAIN_NAME}
      - TA_ENABLE_AUTH_PROXY=true
      - TA_USERNAME=tubearchivist
      - TA_PASSWORD=tubearchivist
      - TA_AUTH_PROXY_USERNAME_HEADER=HTTP_X_AUTHENTIK_USERNAME
      - TA_AUTH_PROXY_LOGOUT_URL=https://auth.${DOMAIN_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tubearchivist.entrypoints=websecure"
      - "traefik.http.routers.tubearchivist.tls=true"
      - "traefik.http.routers.tubearchivist.rule=Host(`tubearchivist.${DOMAIN_NAME}`)"
      - "traefik.http.routers.tubearchivist.middlewares=chain-forwardauth@docker"
      - "traefik.http.services.tubearchivist.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - elasticsearch
      - redis
    restart: unless-stopped
  redis:
    image: redis/redis-stack-server
    expose:
      - "6379"
    env_file:
      - /defaults.env
    volumes:
      - redis:/data
    restart: unless-stopped
  elasticsearch:
    image: bbilly1/tubearchivist-es:8.14.3
    env_file:
      - /defaults.env
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    expose:
      - "9200"
    restart: unless-stopped
networks:
  default:
  traefik:
    external: true
volumes:
  cache:
  redis:
  elasticsearch:
