services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - $DATA_DIR/uptime-kuma:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.${DOMAIN_NAME}`)"
      - "traefik.http.routers.uptime-kuma.middlewares=chain-forwardauth@docker"
      - "traefik.http.routers.uptime-kuma.service=uptime-kuma"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    networks:
      - traefik
    restart: unless-stopped
networks:
  traefik:
    external: true
